@startuml

title  Шардирование в MongoDB
skinparam componentStyle rectangle
skinparam backgroundColor white
skinparam shadowing false

!define APP_COLOR #1976D2
!define DRIVER_COLOR #9E9E9E
!define CONFIG_COLOR #E91E63
!define ROUTER_COLOR #FF9800
!define SHARD_COLOR #E1F5FE
!define PRIMARY_COLOR #4CAF50

rectangle "pymongo-api" as app APP_COLOR

package "MongoDB" {
    rectangle "Драйвер" as driver DRIVER_COLOR
    rectangle "configSrv" as config CONFIG_COLOR
    rectangle "Роутер" as router1 ROUTER_COLOR
    rectangle "Роутер" as router2 ROUTER_COLOR
    rectangle "shard1" as shard1 SHARD_COLOR {
        rectangle "master" as s1_1 PRIMARY_COLOR
    }
    rectangle "shard2" as shard2 SHARD_COLOR {
        rectangle "master" as s2_1 PRIMARY_COLOR
    }
}

app -down-> driver
driver -down-> router1
driver -down-> router2
router1 -up-> config
router2 -up-> config
router1 -down-> shard1
router2 -down-> shard2
router1 .right. router2

@enduml